### ISSUE TITLE
Compiler messages: ERROR: The import com.evnit cannot be resolved

### ISSUE THREAD

**Issue by longtqdayma** [greenjoe/lambdaFromString#7]
I ran the app on tomcat Server 8.5.
My application is a web application using Tomcat 8.5 Java 8, ZK 8.0.3
I ran from-string lambda lambda-1.4.

`public class ChitieuGiao implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Long id;
	private Double trongsochung = 0d;
	private Double chitieugiao = 0d;
	private Double tylethuchien = 0d;
	private Date createTime = new Date();
	private String createUser;

	/** default constructor */
	public ChitieuGiao() {
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Double getTrongsochung() {
		return this.trongsochung;
	}

	public void setTrongsochung(Double trongsochung) {
		this.trongsochung = trongsochung;
	}

	public Double getChitieugiao() {
		return this.chitieugiao;
	}

	public void setChitieugiao(Double chitieugiao) {
		this.chitieugiao = chitieugiao;
	}

	public Double getTylethuchien() {
		return this.tylethuchien;
	}

	public void setTylethuchien(Double tylethuchien) {
		this.tylethuchien = tylethuchien;
	}

	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}`

Code run 

`
	@Command("onExecuted")
	@Override
	public void onExecuted() {
		try {
			exlambda();
		} catch (ParseException e) {
			e.printStackTrace();
		}
	}

public void exlambda() {
		ChitieuGiao chitieu = new ChitieuGiao();
		chitieu.setCreateTime(new Date());
		chitieu.setChitieugiao(9000000000000d);
		chitieu.setTrongsochung(9.0);
		chitieu.setTylethuchien(89.0);
		String code = codeTest();
		try {

			LambdaFactory factory = LambdaFactory.get(LambdaFactoryConfiguration.get().withImports(ChitieuGiao.class));

			Function<ChitieuGiao, Double> lambda = factory.createLambdaUnchecked("tinhdiem -> { " + code + "}",
					new TypeReference<Function<ChitieuGiao, Double>>() {
					});
			System.out.println(lambda.apply(chitieu));

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

public String codeTest() {
		String code = "";
		code = "Double tylethuchien = tinhdiem.getTylethuchien();";
		code += "Double diemhoanthanh = (double) 0;";

		code += "if (tylethuchien <= 100) {";
		code += "	diemhoanthanh = tylethuchien;";
		code += "} else if (tylethuchien > 100 && tylethuchien < 105) {";
		code += "	diemhoanthanh = 100 + 3 * (tylethuchien - 100);";

		code += "} else if (tylethuchien >= 105 && tylethuchien < 110) {";
		code += "	diemhoanthanh = 100 + 3 * 5 + 5 * (tylethuchien - 105);";
		code += "} else if (tylethuchien >= 110 && tylethuchien < 120) {";
		code += "	diemhoanthanh = 100 + 3 * 5 + 5 * 5 + 7 * (tylethuchien - 110);";
		code += "}";
		code += "return diemhoanthanh;";
		return code;
	}`

`pl.joegreen.lambdaFromString.LambdaCreationRuntimeException: pl.joegreen.lambdaFromString.classFactory.ClassCompilationException: Class compilation details:
Class name: LambdaFromStringHelper
Class source:
import java.util.function.*;
import com.evnit.hrms.viewmodel.kpi.ChitieuGiao;

public class LambdaFromStringHelper {
    public static java.util.function.Function<com.evnit.hrms.viewmodel.kpi.ChitieuGiao, java.lang.Double> getLambda() {return (tinhdiem -> { Double tylethuchien = tinhdiem.getTylethuchien();Double diemhoanthanh = (double) 0;if (tylethuchien <= 100) {	diemhoanthanh = tylethuchien;} else if (tylethuchien > 100 && tylethuchien < 105) {	diemhoanthanh = 100 + 3 * (tylethuchien - 100);} else if (tylethuchien >= 105 && tylethuchien < 110) {	diemhoanthanh = 100 + 3 * 5 + 5 * (tylethuchien - 105);} else if (tylethuchien >= 110 && tylethuchien < 120) {	diemhoanthanh = 100 + 3 * 5 + 5 * 5 + 7 * (tylethuchien - 110);}return diemhoanthanh;});}
}
Compiler messages:
ERROR: The import com.evnit cannot be resolved
ERROR: com.evnit cannot be resolved to a type
ERROR: This lambda expression refers to the missing type com.evnit.hrms.viewmodel.kpi.ChitieuGiao
Compiler standard error output:
----------
1. ERROR in \LambdaFromStringHelper.java (at line 2)
	import com.evnit.hrms.viewmodel.kpi.ChitieuGiao;
	       ^^^^^^^^^
The import com.evnit cannot be resolved
----------
2. ERROR in \LambdaFromStringHelper.java (at line 5)
	public static java.util.function.Function<com.evnit.hrms.viewmodel.kpi.ChitieuGiao, java.lang.Double> getLambda() {return (tinhdiem -> { Double tylethuchien = tinhdiem.getTylethuchien();Double diemhoanthanh = (double) 0;if (tylethuchien <= 100) {	diemhoanthanh = tylethuchien;} else if (tylethuchien > 100 && tylethuchien < 105) {	diemhoanthanh = 100 + 3 * (tylethuchien - 100);} else if (tylethuchien >= 105 && tylethuchien < 110) {	diemhoanthanh = 100 + 3 * 5 + 5 * (tylethuchien - 105);} else if (tylethuchien >= 110 && tylethuchien < 120) {	diemhoanthanh = 100 + 3 * 5 + 5 * 5 + 7 * (tylethuchien - 110);}return diemhoanthanh;});}
	                                          ^^^^^^^^^
com.evnit cannot be resolved to a type
----------
3. ERROR in \LambdaFromStringHelper.java (at line 5)
	public static java.util.function.Function<com.evnit.hrms.viewmodel.kpi.ChitieuGiao, java.lang.Double> getLambda() {return (tinhdiem -> { Double tylethuchien = tinhdiem.getTylethuchien();Double diemhoanthanh = (double) 0;if (tylethuchien <= 100) {	diemhoanthanh = tylethuchien;} else if (tylethuchien > 100 && tylethuchien < 105) {	diemhoanthanh = 100 + 3 * (tylethuchien - 100);} else if (tylethuchien >= 105 && tylethuchien < 110) {	diemhoanthanh = 100 + 3 * 5 + 5 * (tylethuchien - 105);} else if (tylethuchien >= 110 && tylethuchien < 120) {	diemhoanthanh = 100 + 3 * 5 + 5 * 5 + 7 * (tylethuchien - 110);}return diemhoanthanh;});}
	                                                                                                                          ^^^^^^^^^^^^
This lambda expression refers to the missing type ChitieuGiao
----------
3 problems (3 errors)

	at pl.joegreen.lambdaFromString.LambdaFactory.createLambdaUnchecked(LambdaFactory.java:101)
	at com.evnit.hrms.viewmodel.kpi.KyApDungVM.exlambda(KyApDungVM.java:123)
	at com.evnit.hrms.viewmodel.kpi.KyApDungVM.onNew(KyApDungVM.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.zkoss.bind.impl.ParamCall.call(ParamCall.java:149)
	at org.zkoss.bind.impl.BinderImpl.doExecute(BinderImpl.java:2025)
	at org.zkoss.bind.impl.BinderImpl.doCommand(BinderImpl.java:1738)
	at org.zkoss.bind.impl.BinderImpl.access$1300(BinderImpl.java:129)
	at org.zkoss.bind.impl.BinderImpl$CommandEventListener.onEvent0(BinderImpl.java:1585)
	at org.zkoss.bind.impl.BinderImpl$CommandEventListener.onEvent(BinderImpl.java:1538)
	at org.zkoss.zk.ui.AbstractComponent.onEvent(AbstractComponent.java:3163)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:3133)
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:3075)
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:138)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.process0(EventProcessingThreadImpl.java:545)
	at org.zkoss.zk.ui.impl.EventProcessingThreadImpl.run(EventProcessingThreadImpl.java:470)
Caused by: pl.joegreen.lambdaFromString.classFactory.ClassCompilationException: Class compilation details:
Class name: LambdaFromStringHelper
Class source:
import java.util.function.*;
import com.evnit.hrms.viewmodel.kpi.ChitieuGiao;

public class LambdaFromStringHelper {
    public static java.util.function.Function<com.evnit.hrms.viewmodel.kpi.ChitieuGiao, java.lang.Double> getLambda() {return (tinhdiem -> { Double tylethuchien = tinhdiem.getTylethuchien();Double diemhoanthanh = (double) 0;if (tylethuchien <= 100) {	diemhoanthanh = tylethuchien;} else if (tylethuchien > 100 && tylethuchien < 105) {	diemhoanthanh = 100 + 3 * (tylethuchien - 100);} else if (tylethuchien >= 105 && tylethuchien < 110) {	diemhoanthanh = 100 + 3 * 5 + 5 * (tylethuchien - 105);} else if (tylethuchien >= 110 && tylethuchien < 120) {	diemhoanthanh = 100 + 3 * 5 + 5 * 5 + 7 * (tylethuchien - 110);}return diemhoanthanh;});}
}
Compiler messages:
ERROR: The import com.evnit cannot be resolved
ERROR: com.evnit cannot be resolved to a type
ERROR: This lambda expression refers to the missing type com.evnit.hrms.viewmodel.kpi.ChitieuGiao
Compiler standard error output:
----------
1. ERROR in \LambdaFromStringHelper.java (at line 2)
	import com.evnit.hrms.viewmodel.kpi.ChitieuGiao;
	       ^^^^^^^^^
The import com.evnit cannot be resolved
----------
2. ERROR in \LambdaFromStringHelper.java (at line 5)
	public static java.util.function.Function<com.evnit.hrms.viewmodel.kpi.ChitieuGiao, java.lang.Double> getLambda() {return (tinhdiem -> { Double tylethuchien = tinhdiem.getTylethuchien();Double diemhoanthanh = (double) 0;if (tylethuchien <= 100) {	diemhoanthanh = tylethuchien;} else if (tylethuchien > 100 && tylethuchien < 105) {	diemhoanthanh = 100 + 3 * (tylethuchien - 100);} else if (tylethuchien >= 105 && tylethuchien < 110) {	diemhoanthanh = 100 + 3 * 5 + 5 * (tylethuchien - 105);} else if (tylethuchien >= 110 && tylethuchien < 120) {	diemhoanthanh = 100 + 3 * 5 + 5 * 5 + 7 * (tylethuchien - 110);}return diemhoanthanh;});}
	                                          ^^^^^^^^^
com.evnit cannot be resolved to a type
----------
3. ERROR in \LambdaFromStringHelper.java (at line 5)
	public static java.util.function.Function<com.evnit.hrms.viewmodel.kpi.ChitieuGiao, java.lang.Double> getLambda() {return (tinhdiem -> { Double tylethuchien = tinhdiem.getTylethuchien();Double diemhoanthanh = (double) 0;if (tylethuchien <= 100) {	diemhoanthanh = tylethuchien;} else if (tylethuchien > 100 && tylethuchien < 105) {	diemhoanthanh = 100 + 3 * (tylethuchien - 100);} else if (tylethuchien >= 105 && tylethuchien < 110) {	diemhoanthanh = 100 + 3 * 5 + 5 * (tylethuchien - 105);} else if (tylethuchien >= 110 && tylethuchien < 120) {	diemhoanthanh = 100 + 3 * 5 + 5 * 5 + 7 * (tylethuchien - 110);}return diemhoanthanh;});}
	                                                                                                                          ^^^^^^^^^^^^
This lambda expression refers to the missing type ChitieuGiao
----------
3 problems (3 errors)

	at pl.joegreen.lambdaFromString.classFactory.DefaultClassFactory.compileClasses(DefaultClassFactory.java:54)
	at pl.joegreen.lambdaFromString.classFactory.DefaultClassFactory.createClass(DefaultClassFactory.java:24)
	at pl.joegreen.lambdaFromString.LambdaFactory.createLambda(LambdaFactory.java:72)
	at pl.joegreen.lambdaFromString.LambdaFactory.createLambdaUnchecked(LambdaFactory.java:99)
	... 18 more
`

**Comment by greenjoe** [comment]
Hello,
by default 
`ClassPathExtractor.getJavaPropertyClassPath()` is used to find out what class path should be used when compiling the lambda. It can fail in application servers like tomcat. 

Please try changing
`LambdaFactoryConfiguration.get().withImports(ChitieuGiao.class)`
into
```LambdaFactoryConfiguration.get()
.withCompilationClassPath(ClassPathExtractor.getCurrentContextClassLoaderClassPath())
.withImports(ChitieuGiao.class)````
and let me know if it helps.

**Comment by kjh15011** [comment]
Hi, I still have same Issue, 
but I couldn't find 
> ClassPathExtractor.getCurrentContextClassLoaderClassPath 
in version 1.7

So I tried like this,
> LambdaFactoryConfiguration.get().withCompilationClassPath(ClassPathExtractor.getUrlClassLoaderClassPath(contextClassLoader)).withImports(MyClass.class)

But, It is not working,

> Compiler messages:
> ERROR: package com.aaa.bbb does not exist
 at pl.joegreen.lambdaFromString.LambdaFactory.createLambda(LambdaFactory.java:91)
...
> Caused by: pl.joegreen.lambdaFromString.classFactory.ClassCompilationException: Class compilation details:
Class name: LambdaFromStringHelper


Is there any way to solve it?
