### ISSUE TITLE
Making Service Calls within Lambda Expressions

### ISSUE THREAD

**Issue by stephenschultz** [greenjoe/lambdaFromString#9]
I have a lambda expression expression makes a service call:

> Predicate<Project> onMP = obj -> (Boolean)reportsService.parseMethods("onMortgagePlan[2017]", obj);

where `reportsService` is an autowired local reference to a service class.

When I attempt to create this lambda using `LambdaFactory`

> LambdaFactory lambdaFactory = LambdaFactory.get(
>         LambdaFactoryConfiguration.get().withImports(Project.class));
> Function<Project, Boolean> onMP = lambdaFactory.createLambda(
>         "obj -> (Boolean)reportsService.parseMethods(\"onMortgagePlan[2017]\", obj)", 
>         new TypeReference<Function<Project, Boolean>>(){});

 I get a `ClassCompilationException`:
 
> Class name: LambdaFromStringHelper
> Class source:
import java.util.function.*;
> import gov.lanl.queue.model.entity.project.Project;
> 
> public class LambdaFromStringHelper {
>     public static java.util.function.Function<gov.lanl.queue.model.entity.project.Project, > java.lang.Boolean> getLambda() {return (obj -> (Boolean)reportsService.parseMethods("onMortgagePlan[2017]", obj));}
> }
> Compiler messages:
> ERROR: cannot find symbol
>   symbol:   variable reportsService
>   location: class LambdaFromStringHelper
> Compiler standard error output:

Is there any way to make this work?

**Comment by greenjoe** [comment]
Hello @stephenschultz  
I can see that I have not specified it clearly in the readme, but the library cannot handle closures - it will not work if lambda tries to use reference that is specified outside the context of the lambda. They have to be passed explicitely as arguments. 

In your case you could change the lambda to be a BiFunction instead of a Function and take ReportsService as another argument: 

```
BiFunction<ReportsService, Project, Boolean> onMP = lambdaFactory.createLambda(
"(reportsService, project) -> (Boolean)reportsService.parseMethods(\"onMortgagePlan[2017]\", project)",
new TypeReference<BiFunction<ReportsService, Project, Boolean>>(){});
onMP.apply(reportsService, project);
```

I hope it helps! :)
